[supervisord]
nodaemon=true
logfile=/app/supervisord.log
pidfile=/app/supervisord.pid

[program:web]
command=python web/server_simple.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/web.err.log
stdout_logfile=/app/web.out.log

[program:telegram]
command=python start_telegram.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/telegram.err.log
stdout_logfile=/app/telegram.out.log