"""
⚡ GENESIS DEPLOYMENT AGENT ⚡
Genesis AI can deploy itself autonomously!
"""

import os
import json
import subprocess
from typing import Dict, Any, Optional
from dataclasses import dataclass
from datetime import datetime

@dataclass
class DeploymentResult:
    success: bool
    message: str
    url: Optional[str] = None
    logs: str = ""

class GenesisDeploymentAgent:
    """Genesis Protocol - Self Deployment Agent"""
    
    VERSION = "2.0.0"
    REPO_URL = "https://github.com/aakash00a1-byte/Genesis-protocol-.git"
    
    PLATFORMS = {
        "railway": "Railway.app",
        "render": "Render.com", 
        "fly": "Fly.io",
        "local": "Localhost"
    }
    
    def __init__(self):
        self.timestamp = datetime.now().isoformat()
        self.deployment_log = []
        
    def log(self, message: str, level: str = "INFO"):
        entry = f"[{datetime.now().strftime('%H:%M:%S')}] [{level}] {message}"
        self.deployment_log.append(entry)
        print(entry)
    
    def deploy(self, platform: str = "railway", target_dir: str = "/tmp/Genesis-protocol",
               api_keys: Optional[Dict[str, str]] = None, start_server: bool = True) -> DeploymentResult:
        """Autonomous deployment method"""
        self.log(f"⚡ Genesis Deployment Agent v{self.VERSION}")
        self.log(f"📦 Target: {platform} | 📁 Dir: {target_dir}")
        
        try:
            if not self._clone_or_update(target_dir):
                return DeploymentResult(False, "Failed to clone repository")
            if not self._setup_env(target_dir, api_keys or {}):
                return DeploymentResult(False, "Failed to setup environment")
            if not self._configure_platform(target_dir, platform):
                return DeploymentResult(False, f"Failed to configure {platform}")
            if not self._install_deps(target_dir):
                return DeploymentResult(False, "Failed to install dependencies")
            
            url = None
            if start_server:
                url = self._start_server(target_dir, platform)
            
            return DeploymentResult(success=True, message=f"✅ Deployed to {platform}", url=url)
        except Exception as e:
            return DeploymentResult(False, f"Deployment failed: {str(e)}")
    
    def _clone_or_update(self, target_dir: str) -> bool:
        self.log("📥 Cloning Genesis Protocol...")
        if os.path.exists(target_dir):
            self.log("   → Updating existing installation...")
            result = subprocess.run(["git", "pull"], cwd=target_dir, capture_output=True)
        else:
            self.log("   → Cloning fresh installation...")
            os.makedirs(os.path.dirname(target_dir), exist_ok=True)
            result = subprocess.run(["git", "clone", self.REPO_URL, target_dir], capture_output=True)
        
        if result.returncode == 0:
            self.log("   ✅ Clone successful")
            return True
        self.log(f"   ❌ Clone failed: {result.stderr}", "ERROR")
        return False
    
    def _setup_env(self, target_dir: str, api_keys: Dict[str, str]) -> bool:
        self.log("⚙️  Configuring environment...")
        env_file = os.path.join(target_dir, ".env")
        
        if os.path.exists(env_file):
            subprocess.run(["cp", env_file, f"{env_file}.backup"])
        
        env_content = f"""# Genesis Protocol - Generated by Genesis Agent
# {self.timestamp}

# AI Providers
GROQ_API_KEY={api_keys.get('GROQ_API_KEY', '')}
OPENAI_API_KEY={api_keys.get('OPENAI_API_KEY', '')}
GEMINI_API_KEY={api_keys.get('GEMINI_API_KEY', '')}
ANTHROPIC_API_KEY={api_keys.get('ANTHROPIC_API_KEY', '')}
DEEPSEEK_API_KEY={api_keys.get('DEEPSEEK_API_KEY', '')}

# Services
TAVILY_API_KEY={api_keys.get('TAVILY_API_KEY', '')}

# App
SECRET_KEY=genesis-{os.urandom(8).hex()}
FLASK_ENV=production
PORT=5000
"""
        with open(env_file, 'w') as f:
            f.write(env_content)
        self.log("   ✅ Environment configured")
        return True
    
    def _configure_platform(self, target_dir: str, platform: str) -> bool:
        self.log(f"🔧 Configuring {platform}...")
        
        if platform == "railway":
            config = {
                "$schema": "https://railway.app/railway.schema.json",
                "build": {"builder": "NIXPACKS"},
                "deploy": {"startCommand": "cd web && python3 app.py"}
            }
            with open(os.path.join(target_dir, "railway.json"), 'w') as f:
                json.dump(config, f, indent=2)
        
        self.log(f"   ✅ {platform} ready")
        return True
    
    def _install_deps(self, target_dir: str) -> bool:
        self.log("🐍 Installing dependencies...")
        venv_dir = os.path.join(target_dir, ".venv")
        req_file = os.path.join(target_dir, "requirements.txt")
        
        if not os.path.exists(venv_dir):
            subprocess.run(["python3", "-m", "venv", venv_dir], capture_output=True)
        
        pip = os.path.join(venv_dir, "bin", "pip")
        if os.path.exists(pip):
            subprocess.run([pip, "install", "-q", "-r", req_file], cwd=target_dir, capture_output=True, timeout=300)
        
        self.log("   ✅ Dependencies installed")
        return True
    
    def _start_server(self, target_dir: str, platform: str) -> Optional[str]:
        self.log("🌐 Starting Genesis Protocol...")
        web_dir = os.path.join(target_dir, "web")
        python = os.path.join(target_dir, ".venv", "bin", "python")
        
        if not os.path.exists(python):
            python = "python3"
        
        os.environ['PORT'] = '5000'
        self.log("   🚀 Starting on http://localhost:5000")
        
        subprocess.run([python, "app.py"], cwd=web_dir)
        return "http://localhost:5000"
    
    def get_status(self) -> Dict[str, Any]:
        return {"version": self.VERSION, "timestamp": self.timestamp, "logs": self.deployment_log}


def deploy(api_keys: Optional[Dict[str, str]] = None) -> DeploymentResult:
    """One-command deployment"""
    agent = GenesisDeploymentAgent()
    return agent.deploy(platform="railway", target_dir="/tmp/Genesis-protocol", api_keys=api_keys)


if __name__ == "__main__":
    print("""
╔═══════════════════════════════════════════════════════════╗
║     ⚡ GENESIS PROTOCOL - AUTONOMOUS DEPLOYMENT ⚡   ║
╚═══════════════════════════════════════════════════════════╝
    """)
    print("Usage: python genesis_deploy_agent.py deploy")
    result = deploy()
    print(f"\nResult: {result.message}")