#!/usr/bin/env python3
"""
⚡ GENESIS PROTOCOL - AUTONOMOUS DEPLOYMENT ENGINE ⚡
Genesis can deploy itself anywhere autonomously!
"""

import os
import sys
import json
import time
import subprocess
import urllib.request
import urllib.error
from datetime import datetime
from pathlib import Path

class GenesisAutonomous:
    """Self-deploying Genesis Protocol Engine"""
    
    def __init__(self):
        self.version = "2.0.0"
        self.repo_url = "https://github.com/aakash00a1-byte/Genesis-protocol-.git"
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
    def log(self, msg, level="INFO"):
        print(f"[{datetime.now().strftime('%H:%M:%S')}] [{level}] {msg}")
    
    def banner(self):
        print("""
╔═══════════════════════════════════════════════════════════╗
║     ⚡ GENESIS PROTOCOL - AUTONOMOUS DEPLOYMENT ⚡       ║
║                                                           ║
║     Self-deploying AI Protocol Engine                     ║
║     Version: {version}                                      ║
║     Time: {time}                                   ║
╚═══════════════════════════════════════════════════════════╝
        """.format(version=self.version, time=self.timestamp))
    
    def check_internet(self):
        """Check internet connectivity"""
        self.log("Checking internet connectivity...")
        try:
            urllib.request.urlopen('https://api.github.com', timeout=5)
            self.log("✓ Internet connection active")
            return True
        except:
            self.log("✗ No internet connection", "ERROR")
            return False
    
    def check_requirements(self):
        """Check system requirements"""
        self.log("Checking system requirements...")
        
        checks = {
            "Python": sys.version_info >= (3, 8),
            "Git": self.run_cmd(["git", "--version"], capture=True),
            "pip": self.run_cmd([sys.executable, "-m", "pip", "--version"], capture=True),
        }
        
        for name, result in checks.items():
            if isinstance(result, bool):
                status = "✓" if result else "✗"
                self.log(f"{status} {name}")
            else:
                status = "✓" if result else "✗"
                self.log(f"{status} {name}: {result if result else 'Not found'}")
        
        return all(isinstance(v, bool) and v for v in checks.values())
    
    def run_cmd(self, cmd, capture=False, cwd=None):
        """Run shell command"""
        try:
            result = subprocess.run(
                cmd, 
                capture_output=capture, 
                text=True, 
                cwd=cwd,
                timeout=120
            )
            return result.stdout.strip() if capture else result.returncode == 0
        except Exception as e:
            return False
    
    def clone_or_update(self, target_dir):
        """Clone or update Genesis"""
        if Path(target_dir).exists():
            self.log(f"Genesis found at {target_dir}, updating...")
            return self.run_cmd(["git", "pull"], cwd=target_dir)
        else:
            self.log(f"Cloning Genesis to {target_dir}...")
            return self.run_cmd(["git", "clone", self.repo_url, target_dir], cwd=os.path.dirname(target_dir))
    
    def setup_virtualenv(self, target_dir):
        """Create and activate virtual environment"""
        venv_dir = Path(target_dir) / ".venv"
        
        if venv_dir.exists():
            self.log("Virtual environment already exists")
        else:
            self.log("Creating virtual environment...")
            if not self.run_cmd([sys.executable, "-m", "venv", str(venv_dir)]):
                return False
        
        self.log("Installing dependencies...")
        pip = venv_dir / "bin" / "pip"
        return self.run_cmd([str(pip), "install", "-q", "-r", "requirements.txt"], cwd=target_dir)
    
    def setup_env(self, target_dir, api_keys=None):
        """Setup environment variables"""
        env_file = Path(target_dir) / ".env"
        
        if env_file.exists():
            self.log(".env already exists, skipping...")
            return True
        
        self.log("Creating .env file...")
        api_keys = api_keys or {}
        
        env_content = f"""# Genesis Protocol - Auto-generated by Genesis Autonomous
# Generated at: {self.timestamp}

# AI Providers
GROQ_API_KEY={api_keys.get('GROQ_API_KEY', 'your_groq_key_here')}
OPENAI_API_KEY={api_keys.get('OPENAI_API_KEY', '')}
GEMINI_API_KEY={api_keys.get('GEMINI_API_KEY', '')}
ANTHROPIC_API_KEY={api_keys.get('ANTHROPIC_API_KEY', '')}
DEEPSEEK_API_KEY={api_keys.get('DEEPSEEK_API_KEY', '')}
MISTRAL_API_KEY={api_keys.get('MISTRAL_API_KEY', '')}
COHERE_API_KEY={api_keys.get('COHERE_API_KEY', '')}
PERPLEXITY_API_KEY={api_keys.get('PERPLEXITY_API_KEY', '')}

# Services
TAVILY_API_KEY={api_keys.get('TAVILY_API_KEY', '')}
TELEGRAM_BOT_TOKEN={api_keys.get('TELEGRAM_BOT_TOKEN', '')}

# App Settings
SECRET_KEY=genesis-autonomous-{os.urandom(8).hex()}
FLASK_ENV=production
PORT=5000
"""
        
        with open(env_file, 'w') as f:
            f.write(env_content)
        
        self.log("✓ .env created")
        return True
    
    def create_railway_config(self, target_dir):
        """Create Railway deployment configuration"""
        self.log("Creating Railway configuration...")
        
        config = {
            "$schema": "https://railway.app/railway.schema.json",
            "build": {
                "builder": "NIXPACKS",
                "buildCommand": "cd web && pip install -r requirements.txt"
            },
            "deploy": {
                "numReplicas": 1,
                "restartPolicyType": "ON_FAILURE",
                "restartPolicyMaxRetries": 10,
                "startCommand": "cd web && python3 app.py",
                "healthCheckPath": "/"
            }
        }
        
        with open(Path(target_dir) / "railway.json", 'w') as f:
            json.dump(config, f, indent=2)
        
        self.log("✓ Railway config created")
        return True
    
    def start_local(self, target_dir):
        """Start Genesis locally"""
        self.log("Starting Genesis Protocol locally...")
        
        web_dir = Path(target_dir) / "web"
        venv_python = Path(target_dir) / ".venv" / "bin" / "python"
        
        if not venv_python.exists():
            venv_python = Path(target_dir) / ".venv" / "Scripts" / "python"  # Windows
        
        os.environ['PORT'] = '5000'
        
        self.log("🚀 Genesis Protocol starting on http://localhost:5000")
        self.log("Press Ctrl+C to stop\n")
        
        subprocess.run([str(venv_python), "app.py"], cwd=str(web_dir), env={**os.environ, 'PORT': '5000'})
    
    def deploy_railway(self, target_dir):
        """Deploy to Railway"""
        self.log("Preparing Railway deployment...")
        
        # Check if Railway CLI is available
        railway_available = self.run_cmd(["railway", "--version"], capture=True)
        
        if railway_available:
            self.log("Railway CLI found, deploying...")
            self.run_cmd(["railway", "login"], cwd=target_dir)
            self.run_cmd(["railway", "init"], cwd=target_dir)
            self.run_cmd(["railway", "up"], cwd=target_dir)
            self.log("✓ Deployed to Railway!")
        else:
            self.log("Railway CLI not found. Use web dashboard:")
            self.log(f"  → https://railway.app/new?template={self.repo_url}")
    
    def run(self, mode="full", target_dir=None, api_keys=None):
        """Run autonomous deployment"""
        self.banner()
        
        if not self.check_internet():
            self.log("Cannot proceed without internet", "ERROR")
            return False
        
        target_dir = target_dir or "/tmp/Genesis-protocol"
        
        steps = []
        
        if mode in ["full", "clone"]:
            steps.extend([
                ("Clone/Update Genesis", lambda: self.clone_or_update(target_dir)),
                ("Setup Environment", lambda: self.setup_env(target_dir, api_keys)),
                ("Create Railway Config", lambda: self.create_railway_config(target_dir)),
                ("Setup Virtual Environment", lambda: self.setup_virtualenv(target_dir)),
            ])
        
        if mode == "full":
            steps.append(("Start Local Server", lambda: self.start_local(target_dir)))
        
        if mode == "railway":
            steps.append(("Deploy to Railway", lambda: self.deploy_railway(target_dir)))
        
        self.log(f"\n{'='*50}")
        self.log(f"Running {len(steps)} deployment steps...")
        self.log(f"{'='*50}\n")
        
        for i, (name, func) in enumerate(steps, 1):
            self.log(f"[{i}/{len(steps)}] {name}...")
            if not func():
                self.log(f"Failed: {name}", "ERROR")
                return False
            time.sleep(0.5)
        
        self.log("\n" + "="*50)
        self.log("✅ DEPLOYMENT SUCCESSFUL!")
        self.log("="*50)
        
        if mode == "full":
            self.log(f"""
📋 Deployment Summary:
   📁 Location: {target_dir}
   🌐 URL: http://localhost:5000
   🚂 Railway: Ready to deploy
   
📌 Next Steps:
   1. Edit {target_dir}/.env with your API keys
   2. Start: python {target_dir}/web/app.py
   3. Deploy: railway.app → Connect repo → Deploy
            """)
        
        return True


def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="⚡ Genesis Protocol - Autonomous Deployment")
    parser.add_argument("--mode", choices=["full", "clone", "railway"], default="full",
                        help="Deployment mode")
    parser.add_argument("--target", default="/tmp/Genesis-protocol",
                        help="Target directory")
    parser.add_argument("--groq-key", help="Groq API Key")
    parser.add_argument("--openai-key", help="OpenAI API Key")
    parser.add_argument("--gemini-key", help="Gemini API Key")
    parser.add_argument("--tavily-key", help="Tavily API Key")
    
    args = parser.parse_args()
    
    api_keys = {
        'GROQ_API_KEY': args.groq_key,
        'OPENAI_API_KEY': args.openai_key,
        'GEMINI_API_KEY': args.gemini_key,
        'TAVILY_API_KEY': args.tavily_key,
    }
    api_keys = {k: v for k, v in api_keys.items() if v}
    
    genesis = GenesisAutonomous()
    genesis.run(mode=args.mode, target_dir=args.target, api_keys=api_keys)


if __name__ == "__main__":
    main()